### ISSUE TITLE
Upgrade magnus for Ruby 4 compat

### ISSUE THREAD

**Issue by pboling** [joker1007/tree_stump#14]
## Issue: tree_stump fails to build on Ruby 4.0 (ruby-head) due to magnus v0.7.1 incompatibility

**UPDATE**: Upgraded to magnus v0.8.2 (released version). Testing to verify Ruby 4.0 compatibility. Will close this issue if 0.8.2 resolves the problem.

### Description

`tree_stump` cannot be installed on Ruby 4.0 (ruby-head) because it depends on `magnus` v0.7.1, which is incompatible with Ruby 4.0's API changes.

### Error Summary

```
error[E0308]: mismatched types - rb_fiber_raise expects *mut VALUE but got *const VALUE
error[E0609]: no field `typed_flag` on type `&rb_sys::RTypedData`
```

### Environment

- **Ruby**: 4.0.0+0 (ruby-head)
- **tree_stump**: v0.1.0
- **magnus**: v0.7.1
- **Platform**: Ubuntu (GitHub Actions)

### Current Dependency

```toml
[dependencies]
magnus = { version = "0.7.1" }
```

### Proposed Solution

Update to a newer version of `magnus` that supports Ruby 4.0:

```toml
[dependencies]
magnus = { version = "0.8" }  # or latest version with Ruby 4.0 support
```

### Reproduction

Create a test file `test_ruby4.rb`:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  
  gem "tree_stump",
    github: "pboling/tree_stump",
    branch: "tree_haver"
end

puts "tree_stump loaded successfully!"
```

Run with ruby-head:
```bash
ruby-install ruby-head
~/.rubies/ruby-head/bin/ruby test_ruby4.rb
# => Build fails with errors shown below
```

### Full Build Error

<details>
<summary>Click to expand</summary>

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

error[E0308]: mismatched types
--> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/magnus-0.7.1/src/fiber.rs:469:21
     |
 466 |                 Value::new(rb_fiber_raise(
     |                            -------------- arguments to this function are incorrect
...
 469 |                     &e.as_rb_value() as *const VALUE,
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ types differ in mutability
     |
     = note: expected raw pointer `*mut u64`
                found raw pointer `*const u64`

error[E0609]: no field `typed_flag` on type `&rb_sys::RTypedData`
--> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/magnus-0.7.1/src/r_typed_data.rs:202:58
    |
202 |                     let typed_flag = typed_data.as_ref().typed_flag;
    |                                                          ^^^^^^^^^^ unknown field
    |
    = note: available fields are: `basic`, `fields_obj`, `type_`, `data`

error: could not compile `magnus` (lib) due to 2 previous errors
cargo failed, exit code 101
```
</details>

### Impact

- Ruby 4.0 compatibility testing is blocked
- CI builds fail on ruby-head
- Cannot test with future Ruby releases

### Temporary Workaround
Mark ruby-head builds as allowed to fail:

```yaml
continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
```

#### Option 1: Update magnus (Recommended)

Update `magnus` to a newer version that supports Ruby 4.0 (v0.8.x if available):

```toml
# ext/tree_stump/Cargo.toml
[dependencies]
magnus = { version = "0.8" }  # or latest version with Ruby 4.0 support
rb-sys = { version = "0.9.119", features = ["stable-api-compiled-fallback"] }
tree-sitter = "~0.22"
libloading = "~0.8.4"
```

**Action Required**: Check https://crates.io/crates/magnus for latest version and Ruby 4.0 compatibility.

#### Option 2: Pin Ruby Version (Temporary Workaround)

Exclude ruby-head from CI until magnus is updated:

```yaml
# .github/workflows/*.yml
strategy:
  matrix:
    exclude:
      - ruby: "ruby-head"
```

Or mark as allowed to fail:

```yaml
continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
```

#### Option 3: File Issue with magnus

If magnus doesn't yet support Ruby 4.0, file an issue at:
https://github.com/matsadler/magnus/issues

### Current Dependency Versions (on my fork)

```toml
# From ext/tree_stump/Cargo.toml
magnus = { version = "0.7.1" }
rb-sys = { version = "0.9.119", features = ["stable-api-compiled-fallback"] }
tree-sitter = "~0.22"
```

### Ruby 4.0 API Changes Affecting magnus

1. **`rb_fiber_raise`**: Now requires `*mut VALUE` instead of `*const VALUE`
2. **`RTypedData`**: The `typed_flag` field has been removed from the struct

### Additional Context

- **Fork**: https://github.com/pboling/tree_stump
- **Branch**: tree_haver
- **Upstream**: Check if upstream tree_stump has addressed this
- **Discovered**: CI build failure on ruby-head (December 2024)
- **Affected Projects**: tree_haver, toml-merge (via tree_haver)

### Next Steps

1. Check if `magnus` v0.8.x or later exists with Ruby 4.0 support
2. Test updating `magnus` dependency in tree_stump
3. If magnus doesn't support Ruby 4.0 yet, consider:
   - Filing issue with magnus project
   - Using temporary workaround to skip ruby-head in CI
   - Investigating alternative Ruby-Rust binding libraries

### Related

- magnus project: https://github.com/matsadler/magnus
- magnus crate: https://crates.io/crates/magnus
- rb-sys: https://github.com/oxidize-rb/rb-sys
- Ruby 4.0 API changes: https://bugs.ruby-lang.org/projects/ruby-master/
- Ruby 4.0 changes affecting fiber and typed data structures

### Real CI Failure

- https://github.com/kettle-rb/tree_haver/actions/runs/20222675910/job/58047521851
